# Generated by Django 6.0 on 2025-12-24 03:15

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_atlanta_tech_updates'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_work_mode',
            field=models.CharField(blank=True, choices=[('REMOTE', 'Remote'), ('ONSITE', 'On-Site'), ('HYBRID', 'Hybrid')], default='REMOTE', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, db_index=True, help_text='Additional location details (building, floor, etc.)', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Short professional bio', null=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('featured_project_1', models.JSONField(blank=True, help_text='Featured project data', null=True)),
                ('featured_project_2', models.JSONField(blank=True, help_text='Featured project data', null=True)),
                ('featured_project_3', models.JSONField(blank=True, help_text='Featured project data', null=True)),
                ('github_repos_count', models.PositiveIntegerField(default=0)),
                ('github_stars_count', models.PositiveIntegerField(default=0)),
                ('github_followers_count', models.PositiveIntegerField(default=0)),
                ('open_to_remote', models.BooleanField(default=True)),
                ('open_to_contract', models.BooleanField(default=False)),
                ('available_for_hire', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', taggit.managers.TaggableManager(blank=True, help_text='Technical skills, frameworks, tools', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.portfolio')),
                ('tech_stack', taggit.managers.TaggableManager(blank=True, help_text='Technologies used', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
